import Link from "next/link";
import { CalendarClock, CalendarDays, CheckCircle2, FileCheck2, FileSignature, FolderOpen, House, ReceiptText, ShieldCheck, UserRound, Wallet } from "lucide-react";

import { Breadcrumbs } from "@/components/shared/breadcrumbs";
import { MoneyDisplay } from "@/components/shared/money-display";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import type { Contract } from "./contract-data";
import { ContractQuickActions } from "./contract-quick-actions";
import { ContractStatusBadge } from "./contract-status-badge";

export function ContractDetailView({ contract, basePath, dashboardHref, tenantBasePath, unitBasePath }: { contract: Contract; basePath: string; dashboardHref: string; tenantBasePath: string; unitBasePath: string }) {
  return <div className="space-y-6"><Breadcrumbs items={[{ label: "Dashboard", href: dashboardHref }, { label: "Contrats", href: basePath }, { label: contract.reference }]} /><PageHeader actions={<ContractQuickActions isDraft={contract.status === "draft"} />} description={`${contract.tenantName} · ${contract.unitLabel} · ${contract.propertyName}`} eyebrow="Dossier contractuel" title={contract.reference} /><div className="flex flex-wrap items-center gap-2"><ContractStatusBadge status={contract.status} />{contract.signedAt && <span className="text-xs text-muted-foreground">Signé le {contract.signedAt}</span>}</div>
    <section aria-label="Indicateurs du contrat" className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[
      { label: "Loyer mensuel", value: <MoneyDisplay amount={contract.rent} currency={contract.currency} />, icon: Wallet },
      { label: "Garantie", value: <MoneyDisplay amount={contract.guarantee} currency={contract.currency} />, icon: ShieldCheck },
      { label: "Prochaine échéance", value: contract.nextDueDate, icon: CalendarClock },
      { label: "Durée", value: `${contract.startDate} → ${contract.endDate}`, icon: CalendarDays },
    ].map(({ label, value, icon: Icon }) => <Card key={label}><CardContent className="p-4"><span className="grid size-9 place-items-center rounded-xl bg-brand-blue/10 text-brand-blue"><Icon className="size-4.5" /></span><p className="mt-3 text-xs text-muted-foreground">{label}</p><div className="mt-1 text-sm font-semibold">{value}</div></CardContent></Card>)}</section>
    <Tabs defaultValue="overview"><div className="overflow-x-auto border-b"><TabsList className="h-11 min-w-max" variant="line"><TabsTrigger value="overview"><FileSignature />Vue générale</TabsTrigger><TabsTrigger value="terms"><FileCheck2 />Conditions</TabsTrigger><TabsTrigger value="due"><CalendarDays />Échéances</TabsTrigger><TabsTrigger value="documents"><FolderOpen />Documents</TabsTrigger></TabsList></div>
      <TabsContent className="mt-5" value="overview"><div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Parties et logement</CardTitle><CardDescription>Rattachements du contrat</CardDescription></CardHeader><CardContent className="space-y-3"><InfoLink href={`${tenantBasePath}/${contract.tenantId}`} icon={UserRound} label="Locataire" value={contract.tenantName} /><InfoLink href={`${unitBasePath}/${contract.unitId}`} icon={House} label="Logement" value={`${contract.unitLabel} · ${contract.propertyName}`} /></CardContent></Card><Card><CardHeader><CardTitle>Calendrier</CardTitle><CardDescription>Période et modalités principales</CardDescription></CardHeader><CardContent className="space-y-3"><InfoRow icon={CalendarDays} label="Période" value={`${contract.startDate} → ${contract.endDate}`} /><InfoRow icon={CalendarClock} label="Paiement" value={`${contract.frequency} · le ${contract.dueDay} du mois`} /><InfoRow icon={ReceiptText} label="Préavis" value={contract.noticePeriod} /></CardContent></Card></div></TabsContent>
      <TabsContent className="mt-5" value="terms"><Card><CardHeader><CardTitle>Conditions particulières</CardTitle><CardDescription>Clauses principales préparées dans le dossier</CardDescription></CardHeader><CardContent className="space-y-3">{contract.clauses.map((clause, index) => <div className="flex gap-3 rounded-xl bg-muted/45 p-4" key={clause}><span className="grid size-6 shrink-0 place-items-center rounded-full bg-brand-blue/10 text-xs font-semibold text-brand-blue">{index + 1}</span><p className="text-sm leading-6">{clause}</p></div>)}</CardContent></Card></TabsContent>
      <TabsContent className="mt-5" value="due"><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Prochaine échéance</CardTitle><CardDescription>Loyer contractuel attendu</CardDescription></CardHeader><CardContent><div className="flex items-center gap-3"><CalendarClock className="size-8 text-brand-blue" /><div><p className="font-semibold">{contract.nextDueDate}</p><MoneyDisplay amount={contract.rent} className="mt-1 text-sm text-muted-foreground" currency={contract.currency} /></div></div></CardContent></Card><Card><CardHeader><CardTitle>Garantie contractuelle</CardTitle><CardDescription>Montant prévu au contrat</CardDescription></CardHeader><CardContent className="flex items-center justify-between"><MoneyDisplay amount={contract.guarantee} className="font-heading text-2xl font-semibold" currency={contract.currency} /><ShieldCheck className="size-7 text-status-paid" /></CardContent></Card></div></TabsContent>
      <TabsContent className="mt-5" value="documents"><Card><CardHeader><CardTitle>Documents contractuels</CardTitle><CardDescription>Documents privés stockés dans Supabase Storage.</CardDescription></CardHeader><CardContent>{contract.documents.length ? <div className="grid gap-3 sm:grid-cols-2">{contract.documents.map((document) => <div className="flex items-center gap-3 rounded-xl border p-4" key={document.id}><span className="grid size-10 place-items-center rounded-xl bg-brand-blue/10 text-brand-blue"><FileSignature /></span><div className="min-w-0 flex-1"><p className="truncate font-medium">{document.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{document.type}</p></div>{document.url ? <Button asChild size="sm" variant="outline"><a href={document.url}>Télécharger</a></Button> : <CheckCircle2 className="size-4 text-status-paid" />}</div>)}</div> : <div className="rounded-xl border border-dashed p-8 text-center"><FolderOpen className="mx-auto size-6 text-muted-foreground" /><p className="mt-3 font-medium">Aucun document joint</p><p className="mt-1 text-sm text-muted-foreground">Ajoutez le bail signé lors de la création du contrat.</p></div>}</CardContent></Card></TabsContent>
    </Tabs></div>;
}

function InfoRow({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) {
  return <div className="flex items-start gap-3 rounded-xl bg-muted/45 p-3"><Icon className="mt-0.5 size-4 text-brand-blue" /><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div></div>;
}

function InfoLink({ href, icon: Icon, label, value }: { href: string; icon: typeof UserRound; label: string; value: string }) {
  return <div className="flex items-center gap-3 rounded-xl bg-muted/45 p-3"><Icon className="size-4 text-brand-blue" /><div className="min-w-0 flex-1"><p className="text-xs text-muted-foreground">{label}</p><Link className="mt-1 block truncate text-sm font-semibold hover:text-brand-blue" href={href}>{value}</Link></div><Button asChild size="sm" variant="ghost"><Link href={href}>Voir</Link></Button></div>;
}
