import { BadgeAlert, Building2, CalendarRange, CircleDollarSign, Percent, ReceiptText, Users } from "lucide-react";

import { EmptyState } from "@/components/shared/empty-state";
import { MoneyDisplay } from "@/components/shared/money-display";
import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { ReportData } from "./report-data";
import { ReportActions } from "./report-actions";
import { ReportChartSection } from "./report-chart-section";

function dateLabel(value: string) { return value.split("-").reverse().join("/"); }
function query(data: ReportData) { const params = new URLSearchParams({ debut: data.filters.startDate, fin: data.filters.endDate, devise: data.filters.currency }); if (data.filters.propertyId) params.set("propriete", data.filters.propertyId); if (data.filters.tenantId) params.set("locataire", data.filters.tenantId); return params.toString(); }

function Kpi({ icon: Icon, label, children, helper }: { icon: typeof CircleDollarSign; label: string; children: React.ReactNode; helper: string }) {
  return <Card><CardContent className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-blue/10 text-brand-blue"><Icon className="size-5" /></span><div><p className="text-xs text-muted-foreground">{label}</p><div className="mt-1 font-heading text-xl font-semibold">{children}</div><p className="mt-1 text-xs text-muted-foreground">{helper}</p></div></CardContent></Card>;
}

function Section({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) {
  return <Card className="scroll-mt-24 break-inside-avoid" id={id}><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card>;
}

export function ReportDashboard({ data }: { data: ReportData }) {
  const currency = data.filters.currency;
  const hasFinancialData = data.summary.expected > 0 || data.summary.collected > 0 || data.summary.arrears > 0;
  const sections = [{ id: "mensuel", label: "Mensuel" }, { id: "proprietes", label: "Propriétés" }, { id: "locataires", label: "Locataires" }, { id: "paiements", label: "Paiements" }, { id: "arrieres", label: "Arriérés" }];
  return <div className="report-print-area space-y-6 sm:space-y-8">
    <PageHeader actions={<ReportActions exportHref={`/api/rapports/export?${query(data)}`} />} description="Analyse réelle des loyers, paiements, locataires, propriétés et arriérés." eyebrow="Analyse financière" title="Rapports" />
    <div className="flex flex-wrap gap-2 print:hidden"><Badge variant="secondary">Données Supabase actualisées</Badge>{sections.map((section) => <Button asChild key={section.id} size="sm" variant="ghost"><a href={`#${section.id}`}>{section.label}</a></Button>)}</div>
    <Card className="print:hidden"><CardContent><form action="/rapports" className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr_1fr_0.7fr_1.2fr_1.2fr_auto]" method="GET"><label className="text-xs font-medium">Début<input className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm" defaultValue={data.filters.startDate} name="debut" type="date" /></label><label className="text-xs font-medium">Fin<input className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm" defaultValue={data.filters.endDate} name="fin" type="date" /></label><label className="text-xs font-medium">Devise<select className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm" defaultValue={currency} name="devise"><option value="USD">USD</option><option value="CDF">CDF</option></select></label><label className="text-xs font-medium">Propriété<select className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm" defaultValue={data.filters.propertyId ?? ""} name="propriete"><option value="">Toutes</option>{data.options.properties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-medium">Locataire<select className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm" defaultValue={data.filters.tenantId ?? ""} name="locataire"><option value="">Tous</option>{data.options.tenants.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Button className="self-end" type="submit"><CalendarRange />Appliquer</Button></form></CardContent></Card>
    <div className="rounded-xl border bg-white p-4 text-sm text-slate-700 dark:bg-card dark:text-card-foreground"><strong>Période :</strong> {dateLabel(data.filters.startDate)} au {dateLabel(data.filters.endDate)} · <strong>Devise :</strong> {currency}</div>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6"><Kpi helper="Échéances de la période" icon={CircleDollarSign} label="Attendu"><MoneyDisplay amount={data.summary.expected} currency={currency} /></Kpi><Kpi helper={`${data.summary.paymentCount} paiement(s)`} icon={ReceiptText} label="Encaissé"><MoneyDisplay amount={data.summary.collected} currency={currency} /></Kpi><Kpi helper="Sur les échéances filtrées" icon={BadgeAlert} label="Solde"><MoneyDisplay amount={data.summary.outstanding} currency={currency} /></Kpi><Kpi helper="Situation actuelle" icon={BadgeAlert} label="Arriérés"><MoneyDisplay amount={data.summary.arrears} currency={currency} /></Kpi><Kpi helper="Encaissé / attendu" icon={Percent} label="Recouvrement">{data.summary.recovery.toFixed(1).replace(".", ",")} %</Kpi><Kpi helper={`${data.summary.occupiedUnits}/${data.summary.unitCount} logements`} icon={Building2} label="Occupation">{data.summary.unitCount ? (data.summary.occupiedUnits / data.summary.unitCount * 100).toFixed(1).replace(".", ",") : "0"} %</Kpi></section>
    {!hasFinancialData ? <EmptyState description="Aucune donnée financière réelle ne correspond aux filtres sélectionnés." icon={CalendarRange} title="Rapport sans mouvement" /> : null}
    <section className="scroll-mt-24" id="mensuel"><ReportChartSection currency={currency} monthly={data.monthly} /></section>
    <Section description="Occupation, loyers, encaissements et impayés par propriété." id="proprietes" title="Rapport par propriété"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="py-3">Propriété</th><th>Logements</th><th>Occupés</th><th>Attendu</th><th>Encaissé</th><th>Arriérés</th></tr></thead><tbody className="divide-y">{data.propertyRows.map((row) => <tr key={row.id}><td className="py-3 font-medium">{row.name}</td><td>{row.units}</td><td>{row.occupied}</td><td><MoneyDisplay amount={row.expected} currency={currency} /></td><td><MoneyDisplay amount={row.collected} currency={currency} /></td><td><MoneyDisplay amount={row.arrears} currency={currency} /></td></tr>)}</tbody></table>{data.propertyRows.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">Aucune propriété dans ce rapport.</p> : null}</div></Section>
    <Section description="Situation contractuelle et financière consolidée par locataire." id="locataires" title="Rapport locataires"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="py-3">Locataire</th><th>Logement</th><th>Attendu</th><th>Encaissé</th><th>Arriérés</th><th>Paiements</th></tr></thead><tbody className="divide-y">{data.tenantRows.map((row) => <tr key={row.id}><td className="py-3"><p className="font-medium">{row.name}</p><p className="text-xs text-muted-foreground">{row.propertyName}</p></td><td>{row.unitLabel}</td><td><MoneyDisplay amount={row.expected} currency={currency} /></td><td><MoneyDisplay amount={row.collected} currency={currency} /></td><td><MoneyDisplay amount={row.arrears} currency={currency} /></td><td>{row.payments}</td></tr>)}</tbody></table>{data.tenantRows.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">Aucun locataire dans ce rapport.</p> : null}</div></Section>
    <Section description="Transactions validées sur la période sélectionnée." id="paiements" title="Rapport des paiements"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="py-3">Référence</th><th>Date</th><th>Locataire</th><th>Logement</th><th>Mode</th><th>Montant</th></tr></thead><tbody className="divide-y">{data.paymentRows.map((row) => <tr key={row.id}><td className="py-3 font-medium">{row.reference}</td><td>{row.date}</td><td>{row.tenantName}</td><td>{row.unitLabel} · {row.propertyName}</td><td>{row.mode}</td><td><MoneyDisplay amount={row.amount} currency={currency} /></td></tr>)}</tbody></table>{data.paymentRows.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">Aucun paiement sur cette période.</p> : null}</div></Section>
    <Section description="Soldes actuellement échus, classés par retard maximal." id="arrieres" title="Rapport des arriérés"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="py-3">Locataire</th><th>Bien</th><th>Échéances</th><th>Plus ancien retard</th><th>Solde</th></tr></thead><tbody className="divide-y">{data.arrearsRows.map((row) => <tr key={row.id}><td className="py-3 font-medium">{row.tenantName}</td><td>{row.unitLabel} · {row.propertyName}</td><td>{row.invoiceCount}</td><td>{row.maximumDaysLate} jours</td><td><MoneyDisplay amount={row.totalBalance} currency={currency} /></td></tr>)}</tbody></table>{data.arrearsRows.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">Aucun arriéré dans cette devise.</p> : null}</div></Section>
    <footer className="hidden border-t pt-4 text-xs text-slate-500 print:block">AMIRANDA EMPIRE · Rapport généré depuis les données enregistrées dans Supabase.</footer>
  </div>;
}
