import { CheckCircle2 } from "lucide-react";

import { BrandMark } from "@/components/brand/brand-mark";
import { Breadcrumbs } from "@/components/shared/breadcrumbs";
import { MoneyDisplay } from "@/components/shared/money-display";
import { PageHeader } from "@/components/shared/page-header";
import { Separator } from "@/components/ui/separator";

import { PaymentModeBadge, PaymentStatusBadge } from "./payment-badges";
import type { Payment } from "./payment-data";
import { ReceiptActions } from "./receipt-actions";

export function ReceiptDetailView({ payment, basePath, dashboardHref }: { payment: Payment; basePath: string; dashboardHref: string }) {
  return <div className="space-y-6"><div className="print:hidden"><Breadcrumbs items={[{ label: "Dashboard", href: dashboardHref }, { label: "Reçus", href: basePath }, { label: payment.receiptNumber }]} /><PageHeader actions={<ReceiptActions />} description="Justificatif officiel de l’encaissement" eyebrow="Reçu de paiement" title={payment.receiptNumber} /></div><article className="receipt-print-area mx-auto max-w-3xl overflow-hidden rounded-2xl border bg-white text-slate-950 shadow-sm print:max-w-none print:rounded-none print:border-0 print:shadow-none"><header className="flex flex-col gap-6 border-b border-slate-200 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-10"><BrandMark /><div className="sm:text-right"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">Reçu de paiement</p><h1 className="mt-2 font-heading text-2xl font-semibold">{payment.receiptNumber}</h1><div className="mt-2"><PaymentStatusBadge status={payment.status} /></div></div></header><div className="p-6 sm:p-10"><section className="grid gap-6 sm:grid-cols-2"><ReceiptInfo label="Locataire" value={payment.tenantName} /><ReceiptInfo label="Logement" value={`${payment.unitLabel} · ${payment.propertyName}`} /><ReceiptInfo label="Période d’encaissement" value={payment.period} /><ReceiptInfo label="Date d’encaissement" value={`${payment.date} à ${payment.time}`} /></section><div className="my-8 rounded-2xl bg-blue-950 p-6 text-center text-white"><p className="text-xs font-medium uppercase tracking-[0.16em] text-blue-200">Montant payé</p><MoneyDisplay amount={payment.amount} className="mt-2 font-heading text-4xl font-semibold" currency={payment.currency} /></div><section className="grid gap-4 sm:grid-cols-3"><ReceiptInfo label="Mode de paiement" value={<PaymentModeBadge mode={payment.mode} />} /><ReceiptInfo label="Solde restant" value={<MoneyDisplay amount={payment.balanceAfter} currency={payment.currency} />} /><ReceiptInfo label="Agent" value={payment.agent} /></section><Separator className="my-8 bg-slate-200" /><section><h2 className="text-sm font-semibold">Affectation réelle du paiement</h2><div className="mt-3 space-y-2">{payment.allocations.length ? payment.allocations.map((allocation) => <div className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm" key={`${allocation.period}-${allocation.amount}`}><span>{allocation.period}</span><MoneyDisplay amount={allocation.amount} className="font-semibold" currency={payment.currency} /></div>) : <p className="text-sm text-slate-500">Aucune affectation enregistrée.</p>}</div></section><footer className="mt-10 border-t border-slate-200 pt-6"><p className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 className="size-4 text-emerald-600" />Paiement enregistré sous la référence {payment.reference}</p><p className="mt-2 text-xs leading-5 text-slate-500">Ce reçu reprend les données enregistrées dans AMIRANDA EMPIRE.</p></footer></div></article></div>;
}

function ReceiptInfo({ label, value }: { label: string; value: React.ReactNode }) {
  return <div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><div className="mt-1.5 text-sm font-semibold text-slate-950">{value}</div></div>;
}
